In [1]:
import sys
from pathlib import Path
import os 
sys.path.append('/home/gridsan/vyuan/.local/lib/python3.9/site-packages/')

current_path = Path.cwd()

# Go to top of the root and append
root = current_path.parents[1]
sys.path.append(str(root))

os.chdir(root)

## Imports

In [2]:
import torch
from pathlib import Path
import torch.nn.functional as F


In [3]:
balanced = Path('saved_models/imSitu/200_verbs/CBM/gender/ic_0.3_lam_0.0007_cc_0.2/balanced/imSitu_200_balanced_imSitu_200_gender')
imbalanced_1 = Path('saved_models/imSitu/200_verbs/CBM/gender/ic_0.3_lam_0.0007_cc_0.2/imbalanced_1/imSitu_200_imbalanced_1_imSitu_200_wc')
imbalanced_2 = Path('saved_models/imSitu/200_verbs/CBM/gender/ic_0.3_lam_0.0007_cc_0.2/imbalanced_2/imSitu_200_imbalanced_2_imSitu_200_wc')
male = Path('saved_models/imSitu/200_verbs/CBM/gender/ic_0.3_lam_0.0007_cc_0.2/male/imSitu_200_male_imSitu_200_wc')
female = Path('saved_models/imSitu/200_verbs/CBM/gender/ic_0.3_lam_0.0007_cc_0.2/female/imSitu_200_female_imSitu_200_wc')

In [4]:
W_c_b = torch.load(balanced / 'W_c.pt', map_location='cpu')
W_c_b = W_c_b.to('cuda')

W_c_ib1 = torch.load(imbalanced_1 / 'W_c.pt', map_location='cpu')
W_c_ib1 = W_c_ib1.to('cuda')

W_c_ib2 = torch.load(imbalanced_2 / 'W_c.pt', map_location='cpu')
W_c_ib2 = W_c_ib2.to('cuda')

W_c_male = torch.load(male / 'W_c.pt', map_location='cpu')
W_c_male = W_c_male.to('cuda')

W_c_female = torch.load(female / 'W_c.pt', map_location='cpu')
W_c_female = W_c_female.to('cuda')

In [5]:
def cosine_similarity(layer_a, layer_b):
    # Flatten the weight matrices
    vector_a = layer_a.flatten()
    vector_b = layer_b.flatten()

    # Compute and return cosine similarity
    return F.cosine_similarity(vector_a.unsqueeze(0), vector_b.unsqueeze(0))


In [8]:
cosine_b_ib1 = cosine_similarity(W_c_b, W_c_ib1)
cosine_b_ib2 = cosine_similarity(W_c_b, W_c_ib2)
cosine_b_m = cosine_similarity(W_c_b, W_c_male)
cosine_b_f = cosine_similarity(W_c_b, W_c_female)

In [9]:
print(cosine_b_ib1)
print(cosine_b_ib2)
print(cosine_b_m)
print(cosine_b_f)

tensor([0.3570], device='cuda:0', grad_fn=<DivBackward0>)
tensor([0.3708], device='cuda:0', grad_fn=<DivBackward0>)
tensor([0.3573], device='cuda:0', grad_fn=<DivBackward0>)
tensor([0.3560], device='cuda:0', grad_fn=<DivBackward0>)


In [12]:
cosine_ib1_ib2 = cosine_similarity(W_c_ib1, W_c_ib2)
cosine_ib1_m = cosine_similarity(W_c_ib1, W_c_male)
cosine_ib1_f = cosine_similarity(W_c_ib1, W_c_female)

In [13]:
print(cosine_ib1_ib2)
print(cosine_ib1_m)
print(cosine_ib1_f)

tensor([0.1500], device='cuda:0', grad_fn=<DivBackward0>)
tensor([0.3592], device='cuda:0', grad_fn=<DivBackward0>)
tensor([0.3422], device='cuda:0', grad_fn=<DivBackward0>)


In [14]:
cosine_ib2_m = cosine_similarity(W_c_ib2, W_c_male)
cosine_ib2_f = cosine_similarity(W_c_ib2, W_c_female)

In [15]:
print(cosine_ib2_m)
print(cosine_ib2_f)

tensor([0.3556], device='cuda:0', grad_fn=<DivBackward0>)
tensor([0.3570], device='cuda:0', grad_fn=<DivBackward0>)


In [16]:
cosine_m_f = cosine_similarity(W_c_male, W_c_female)

In [17]:
print(cosine_m_f)

tensor([0.4059], device='cuda:0', grad_fn=<DivBackward0>)
